// <auto-generated />
namespace EdsBikeRides.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _16042013 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_16042013));
        
        string IMigrationMetadata.Id
        {
            get { return "201304161613350_16-04-2013"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
