// <auto-generated />
namespace EdsBikeRides.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _28082013 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_28082013));
        
        string IMigrationMetadata.Id
        {
            get { return "201308291006295_28-08-2013"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
